export const NAME_PAGE = {
  USER_LOGIN_PAGE: {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
  },

  ALLJOB_PAGE: {
    GET_ALL_JOB: "GET_ALL_JOB",
    GET_ALL_POSITION: "GET_ALL_POSITION",
    GET_ALL_LOCATION: "GET_ALL_LOCATION",
    GET_ALL_CATEGORY: "GET_ALL_CATEGORY",
    GET_ALL_USER: "GET_ALL_USER",

    GET_POST_BY_CATEGORY: "GET_POST_BY_CATEGORY",
    GET_POST_BY_POSITION: "GET_POST_BY_POSITION",
    GET_POST_BY_LOCATION: "GET_POST_BY_LOCATION",
  },

  JOB_DETAIL_PAGE: {
    GET_JOB_DETAIL: "GET_JOB_DETAIL",
  },
};
